# Profile: Workstation (Windows 10/11)
# CIS Microsoft Windows 10 Enterprise Benchmark v2.0 - Level 1 + Level 2
# Generated by HardenedGPO module

@{
    ProfileName = "Workstation"
    Description = "Full CIS L1+L2 hardened baseline for Windows 10/11 endpoints"

    GptTmpl = @"
[Unicode]
Unicode=yes
[Version]
signature="`$CHICAGO`$"
Revision=1

; ==============================================================================
; SECTION 1 - ACCOUNT POLICIES
; CIS 1.1 Password Policy
; ==============================================================================
[System Access]
MinimumPasswordAge = 1
MaximumPasswordAge = 365
MinimumPasswordLength = 14
PasswordComplexity = 1
PasswordHistorySize = 24
ClearTextPassword = 0
LockoutBadCount = 5
ResetLockoutCount = 15
LockoutDuration = 15
RequireLogonToChangePassword = 0
ForceLogoffWhenHourExpire = 1
; Rename built-in accounts (CIS 2.3.1.3 / 2.3.1.4)
NewAdministratorName = "LocalAdmin"
NewGuestName = "LocalGuest"
EnableAdminAccount = 0
EnableGuestAccount = 0

; ==============================================================================
; SECTION 17 - ADVANCED AUDIT POLICY (maps to auditpol subcategories)
; CIS 17.x - Success=1, Failure=2, Both=3, None=0
; ==============================================================================
[Event Audit]
AuditSystemEvents = 3
AuditLogonEvents = 3
AuditObjectAccess = 3
AuditPrivilegeUse = 3
AuditPolicyChange = 3
AuditAccountManage = 3
AuditProcessTracking = 1
AuditDSAccess = 0
AuditAccountLogon = 3

; ==============================================================================
; SECTION 2.2 - USER RIGHTS ASSIGNMENT
; ==============================================================================
[Privilege Rights]
; CIS 2.2.2 - Act as part of the OS (empty)
SeTcbPrivilege =
; CIS 2.2.7 - Back up files and directories
SeBackupPrivilege = *S-1-5-32-544
; CIS 2.2.10 - Create a pagefile
SeCreatePagefilePrivilege = *S-1-5-32-544
; CIS 2.2.11 - Create a token object (empty)
SeCreateTokenPrivilege =
; CIS 2.2.13 - Create permanent shared objects (empty)
SeCreatePermanentPrivilege =
; CIS 2.2.15 - Debug programs (Admins only)
SeDebugPrivilege = *S-1-5-32-544
; CIS 2.2.16 - Deny access to this computer from the network
SeDenyNetworkLogonRight = *S-1-5-32-546,*S-1-5-114
; CIS 2.2.19 - Deny local logon
SeDenyInteractiveLogonRight = *S-1-5-32-546
; CIS 2.2.20 - Deny RDP logon
SeDenyRemoteInteractiveLogonRight = *S-1-5-32-546,*S-1-5-114
; CIS 2.2.21 - Enable computer and user accounts to be trusted for delegation (empty)
SeEnableDelegationPrivilege =
; CIS 2.2.22 - Force shutdown from remote (Admins only)
SeRemoteShutdownPrivilege = *S-1-5-32-544
; CIS 2.2.23 - Generate security audits
SeAuditPrivilege = *S-1-5-19,*S-1-5-20
; CIS 2.2.24 - Impersonate client after authentication
SeImpersonatePrivilege = *S-1-5-32-544,*S-1-5-19,*S-1-5-20,*S-1-5-6
; CIS 2.2.29 - Shut down the system
SeShutdownPrivilege = *S-1-5-32-544
; CIS 2.2.30 - Take ownership
SeTakeOwnershipPrivilege = *S-1-5-32-544
; CIS 2.2.6 - Allow RDP logon (Admins + Remote Desktop Users)
SeRemoteInteractiveLogonRight = *S-1-5-32-544,*S-1-5-32-555
; Create symbolic links (Admins only)
SeCreateSymbolicLinkPrivilege = *S-1-5-32-544
; Restore files (Admins only)
SeRestorePrivilege = *S-1-5-32-544

; ==============================================================================
; SECTION 2.3 + 18 - REGISTRY VALUES (Security Options + GP Settings)
; Format: path=type,value  (type 4=DWORD, 1=string, 3=binary, 2=expand string)
; ==============================================================================
[Registry Values]

; --- 2.3.1 Accounts ---
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableGuestAccount=4,0
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\LimitBlankPasswordUse=4,1

; --- 2.3.2 Audit ---
MACHINE\System\CurrentControlSet\Control\Lsa\CrashOnAuditFail=4,0

; --- 2.3.6 Domain Member ---
MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\RequireSignOrSeal=4,1
MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\SealSecureChannel=4,1
MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\SignSecureChannel=4,1
MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\DisablePasswordChange=4,0
MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\MaximumPasswordAge=4,30
MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\RequireStrongKey=4,1

; --- 2.3.7 Interactive Logon ---
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\DontDisplayLastUserName=4,1
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\DisableCAD=4,0
MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\CachedLogonsCount=1,"4"
MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\PasswordExpiryWarning=4,14
MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\ForceUnlockLogon=4,1
; L2: Do not display user info when locked
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\DontDisplayLockedUserId=4,3
; L2: Disable ARSO
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\DisableAutomaticRestartSignOn=4,1

; --- 2.3.8 MS Network Client ---
MACHINE\System\CurrentControlSet\Services\LanManWorkstation\Parameters\RequireSecuritySignature=4,1
MACHINE\System\CurrentControlSet\Services\LanManWorkstation\Parameters\EnableSecuritySignature=4,1
MACHINE\System\CurrentControlSet\Services\LanManWorkstation\Parameters\EnablePlainTextPassword=4,0

; --- 2.3.9 MS Network Server ---
MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\AutoDisconnect=4,15
MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\RequireSecuritySignature=4,1
MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\EnableSecuritySignature=4,1
MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\EnableForcedLogOff=4,1
; L2: SPN target name validation
MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\SmbServerNameHardeningLevel=4,1

; --- 2.3.10 Network Access ---
MACHINE\System\CurrentControlSet\Control\Lsa\DisableDomainCreds=4,1
MACHINE\System\CurrentControlSet\Control\Lsa\EveryoneIncludesAnonymous=4,0
MACHINE\System\CurrentControlSet\Control\Lsa\RestrictAnonymousSAM=4,1
MACHINE\System\CurrentControlSet\Control\Lsa\RestrictAnonymous=4,1
MACHINE\System\CurrentControlSet\Control\Lsa\pku2u\AllowOnlineID=4,0
; L2: restrict remote SAM calls
MACHINE\System\CurrentControlSet\Control\Lsa\RestrictRemoteSAM=1,"O:BAG:BAD:(A;;RC;;;BA)"

; --- 2.3.11 Network Security ---
MACHINE\System\CurrentControlSet\Control\Lsa\NoLMHash=4,1
MACHINE\System\CurrentControlSet\Control\Lsa\LmCompatibilityLevel=4,5
MACHINE\System\CurrentControlSet\Control\Lsa\LDAPClientIntegrity=4,1
MACHINE\System\CurrentControlSet\Control\Lsa\MSV1_0\NTLMMinClientSec=4,537395200
MACHINE\System\CurrentControlSet\Control\Lsa\MSV1_0\NTLMMinServerSec=4,537395200
; L2: Restrict NTLM outgoing traffic
MACHINE\System\CurrentControlSet\Control\Lsa\RestrictSendingNTLMTraffic=4,2

; --- 2.3.13 Shutdown ---
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\ShutdownWithoutLogon=4,0

; --- 2.3.15 System Objects ---
MACHINE\System\CurrentControlSet\Control\Session Manager\ProtectionMode=4,1

; --- 2.3.17 UAC ---
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\FilterAdministratorToken=4,1
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorAdmin=4,2
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorUser=4,0
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableInstallerDetection=4,1
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableSecureUIAPaths=4,1
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA=4,1
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\PromptOnSecureDesktop=4,1
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableVirtualization=4,1

; --- 9.x Windows Firewall ---
MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\EnableFirewall=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\DisableNotifications=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\DefaultInboundAction=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\DefaultOutboundAction=4,0
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\EnableFirewall=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\DisableNotifications=4,0
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\DefaultInboundAction=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\DefaultOutboundAction=4,0
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\EnableFirewall=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\DisableNotifications=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\DefaultInboundAction=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\DefaultOutboundAction=4,0
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\AllowLocalPolicyMerge=4,0
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\AllowLocalIPsecPolicyMerge=4,0
; L2: Firewall logging
MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging\LogDroppedPackets=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging\LogSuccessfulConnections=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging\LogFileSize=4,16384
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging\LogDroppedPackets=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging\LogSuccessfulConnections=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging\LogFileSize=4,16384
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging\LogDroppedPackets=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging\LogSuccessfulConnections=4,1
MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging\LogFileSize=4,16384

; --- 18.1 Control Panel ---
MACHINE\Software\Policies\Microsoft\Windows\Personalization\NoLockScreenCamera=4,1
MACHINE\Software\Policies\Microsoft\Windows\Personalization\NoLockScreenSlideshow=4,1
MACHINE\Software\Policies\Microsoft\Windows\System\AllowOnlineTips=4,0

; --- 18.3 LAPS ---
MACHINE\Software\Policies\Microsoft Services\AdmPwd\AdmPwdEnabled=4,1

; --- 18.4 MSS ---
MACHINE\System\CurrentControlSet\Control\Session Manager\Kernel\DisableExceptionChainValidation=4,0
MACHINE\System\CurrentControlSet\Services\Tcpip6\Parameters\DisableIPSourceRouting=4,2
MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\DisableIPSourceRouting=4,2
MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\EnableICMPRedirect=4,0
MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\PerformRouterDiscovery=4,0
MACHINE\System\CurrentControlSet\Control\Session Manager\SafeDllSearchMode=4,1
MACHINE\System\CurrentControlSet\Control\Session Manager\ScreenSaverGracePeriod=1,"5"
MACHINE\System\CurrentControlSet\Control\Lsa\WarningLevel=4,90
; L2 MSS
MACHINE\System\CurrentControlSet\Services\Netbt\Parameters\NoNameReleaseOnDemand=4,1
MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\KeepAliveTime=4,300000
MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\TcpMaxDataRetransmissions=4,3

; --- 18.5 Network ---
MACHINE\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths\\\*\NETLOGON=1,"RequireMutualAuthentication=1,RequireIntegrity=1"
MACHINE\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths\\\*\SYSVOL=1,"RequireMutualAuthentication=1,RequireIntegrity=1"
MACHINE\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy\fBlockNonDomain=4,1
MACHINE\Software\Policies\Microsoft\Windows NT\DNSClient\EnableMulticast=4,0
; L2 Network
MACHINE\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy\fMinimizeConnections=4,3

; --- 18.6 Printers ---
MACHINE\Software\Policies\Microsoft\Windows NT\Printers\DisableWebPnPDownload=4,1
MACHINE\Software\Policies\Microsoft\Windows NT\Printers\DisableHTTPPrinting=4,1

; --- 18.8 System ---
MACHINE\Software\Policies\Microsoft\Windows\System\DontDisplayNetworkSelectionUI=4,1
MACHINE\Software\Policies\Microsoft\Windows\System\DontEnumerateConnectedUsers=4,1
MACHINE\Software\Policies\Microsoft\Windows\System\EnumerateLocalUsers=4,0
MACHINE\Software\Policies\Microsoft\Windows\System\BlockUserFromShowingAccountDetailsOnSignin=4,1
MACHINE\Software\Policies\Microsoft\Windows\System\NoLocalPasswordResetQuestions=4,1
MACHINE\Software\Policies\Microsoft\Windows\System\EnableSmartScreen=4,1
MACHINE\Software\Policies\Microsoft\Windows\System\DisableLockScreenAppNotifications=4,1
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\PreXPSP2ShellProtocolBehavior=4,0

; --- 18.9.8 AutoPlay ---
MACHINE\Software\Policies\Microsoft\Windows\Explorer\NoAutoplayfornonVolume=4,1
MACHINE\Software\Policies\Microsoft\Windows\Explorer\NoAutorun=4,1
MACHINE\Software\Policies\Microsoft\Windows\Explorer\NoDriveTypeAutoRun=4,255

; --- 18.9.11 BitLocker ---
MACHINE\Software\Policies\Microsoft\FVE\OSManageDRA=4,1
MACHINE\Software\Policies\Microsoft\FVE\OSRecovery=4,1
MACHINE\Software\Policies\Microsoft\FVE\OSEncryptionType=4,1
MACHINE\Software\Policies\Microsoft\FVE\FDVEncryptionType=4,1
MACHINE\Software\Policies\Microsoft\FVE\RDVDenyWriteAccess=4,1

; --- 18.9.12 Camera (L2) ---
MACHINE\Software\Policies\Microsoft\Camera\AllowCamera=4,0

; --- 18.9.14 Cloud Content (L2) ---
MACHINE\Software\Policies\Microsoft\Windows\CloudContent\DisableWindowsConsumerFeatures=4,1

; --- 18.9.15 Credential UI ---
MACHINE\Software\Policies\Microsoft\Windows\CredUI\DisablePasswordReveal=4,1
MACHINE\Software\Policies\Microsoft\Windows\CredUI\EnumerateAdministrators=4,0

; --- 18.9.16 Data Collection / Telemetry ---
MACHINE\Software\Policies\Microsoft\Windows\DataCollection\AllowTelemetry=4,1
MACHINE\Software\Policies\Microsoft\Windows\DataCollection\LimitEnhancedDiagnosticDataWindowsAnalytics=4,1
MACHINE\Software\Policies\Microsoft\Windows\DataCollection\DisableDiagnosticDataViewer=4,1
; L2
MACHINE\Software\Policies\Microsoft\Windows\DataCollection\DisableEnterpriseAuthProxy=4,1

; --- 18.9.26 Event Log ---
MACHINE\Software\Policies\Microsoft\Windows\EventLog\Application\MaxSize=4,32768
MACHINE\Software\Policies\Microsoft\Windows\EventLog\Security\MaxSize=4,196608
MACHINE\Software\Policies\Microsoft\Windows\EventLog\Setup\MaxSize=4,32768
MACHINE\Software\Policies\Microsoft\Windows\EventLog\System\MaxSize=4,32768

; --- 18.9.29 Device Guard / VBS ---
MACHINE\Software\Policies\Microsoft\Windows\DeviceGuard\EnableVirtualizationBasedSecurity=4,1
MACHINE\Software\Policies\Microsoft\Windows\DeviceGuard\RequirePlatformSecurityFeatures=4,3
MACHINE\Software\Policies\Microsoft\Windows\DeviceGuard\HypervisorEnforcedCodeIntegrity=4,1
MACHINE\Software\Policies\Microsoft\Windows\DeviceGuard\LsaCfgFlags=4,1

; --- 18.9.31 File Explorer ---
MACHINE\Software\Policies\Microsoft\Windows\Explorer\TurnOffDataExecutionPreventionForExplorer=4,0
MACHINE\Software\Policies\Microsoft\Windows\Explorer\NoHeapTerminationOnCorruption=4,0

; --- 18.9.33 HomeGroup ---
MACHINE\Software\Policies\Microsoft\Windows\HomeGroup\DisableHomeGroup=4,1

; --- 18.9.45 Logon ---
MACHINE\Software\Policies\Microsoft\Windows\System\BlockDomainPicturePassword=4,1
MACHINE\Software\Policies\Microsoft\Windows\System\AllowDomainPINLogon=4,0

; --- 18.9.47 Microsoft Defender ---
MACHINE\Software\Policies\Microsoft\Windows Defender\MpEngine\MpEnablePus=4,1
MACHINE\Software\Policies\Microsoft\Windows Defender\Real-Time Protection\DisableBehaviorMonitoring=4,0
MACHINE\Software\Policies\Microsoft\Windows Defender\Real-Time Protection\DisableIOAVProtection=4,0
MACHINE\Software\Policies\Microsoft\Windows Defender\Real-Time Protection\DisableRealtimeMonitoring=4,0
MACHINE\Software\Policies\Microsoft\Windows Defender\Real-Time Protection\DisableScriptScanning=4,0
MACHINE\Software\Policies\Microsoft\Windows Defender\Reporting\DisableEnhancedNotifications=4,0
MACHINE\Software\Policies\Microsoft\Windows Defender\Scan\DisableEmailScanning=4,0
MACHINE\Software\Policies\Microsoft\Windows Defender\Scan\DisableRemovableDriveScanning=4,0
MACHINE\Software\Policies\Microsoft\Windows Defender\SpyNet\LocalSettingOverrideSpynetReporting=4,0
MACHINE\Software\Policies\Microsoft\Windows Defender\SpyNet\SpynetReporting=4,2
MACHINE\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\ExploitGuard_ASR_Rules=4,1
MACHINE\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection\EnableNetworkProtection=4,1

; --- 18.9.58 OneDrive ---
MACHINE\Software\Policies\Microsoft\Windows\OneDrive\DisableFileSyncNGSC=4,1

; --- 18.9.65 Remote Desktop ---
MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services\fEncryptionLevel=4,3
MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services\fDisableCdm=4,1
MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services\UserAuthentication=4,1
MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services\SecurityLayer=4,2
MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services\MaxIdleTime=4,900000
MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services\MaxDisconnectionTime=4,60000
MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services\fDisableAutomaticReconnect=4,1

; --- 18.9.80 Windows Hello ---
MACHINE\Software\Policies\Microsoft\PassportForWork\Enabled=4,0

; --- 18.9.85 Windows Installer ---
MACHINE\Software\Policies\Microsoft\Windows\Installer\EnableUserControl=4,0
MACHINE\Software\Policies\Microsoft\Windows\Installer\AlwaysInstallElevated=4,0

; --- 18.9.86 Windows Logon ---
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\DisableAutomaticRestartSignOn=4,1

; --- 18.9.95 PowerShell ---
MACHINE\Software\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging\EnableScriptBlockLogging=4,1
MACHINE\Software\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging\EnableScriptBlockInvocationLogging=4,1
MACHINE\Software\Policies\Microsoft\Windows\PowerShell\Transcription\EnableTranscripting=4,1
MACHINE\Software\Policies\Microsoft\Windows\PowerShell\Transcription\EnableInvocationHeader=4,1
MACHINE\Software\Policies\Microsoft\Windows\PowerShell\ModuleLogging\EnableModuleLogging=4,1

; --- 18.9.102 WinRM ---
MACHINE\Software\Policies\Microsoft\Windows\WinRM\Client\AllowBasic=4,0
MACHINE\Software\Policies\Microsoft\Windows\WinRM\Client\AllowUnencryptedTraffic=4,0
MACHINE\Software\Policies\Microsoft\Windows\WinRM\Client\AllowDigest=4,0
MACHINE\Software\Policies\Microsoft\Windows\WinRM\Service\AllowBasic=4,0
MACHINE\Software\Policies\Microsoft\Windows\WinRM\Service\AllowUnencryptedTraffic=4,0
MACHINE\Software\Policies\Microsoft\Windows\WinRM\Service\DisableRunAs=4,1

; --- 18.9.108 Windows Update ---
MACHINE\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\NoAutoUpdate=4,0
MACHINE\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\AUOptions=4,4
MACHINE\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\AutoInstallMinorUpdates=4,1
MACHINE\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\NoAutoRebootWithLoggedOnUsers=4,0
MACHINE\Software\Policies\Microsoft\Windows\WindowsUpdate\DeferFeatureUpdates=4,1
MACHINE\Software\Policies\Microsoft\Windows\WindowsUpdate\SetDisablePauseUXAccess=4,1
MACHINE\Software\Policies\Microsoft\Windows\WindowsUpdate\SetDisableUXWUAccess=4,1
; L2
MACHINE\Software\Policies\Microsoft\Windows\WindowsUpdate\DeferQualityUpdates=4,1

; --- Credential Guard / WDigest ---
MACHINE\System\CurrentControlSet\Control\SecurityProviders\WDigest\UseLogonCredential=4,0
MACHINE\System\CurrentControlSet\Control\Lsa\RunAsPPL=4,1

; ==============================================================================
; SECTION 5 - SYSTEM SERVICES (Disabled = startup type 4)
; ==============================================================================
[Service General Setting]
BTAGService,4,"D:AR"
bthserv,4,"D:AR"
Browser,4,"D:AR"
MapsBroker,4,"D:AR"
lfsvc,4,"D:AR"
irmon,4,"D:AR"
SharedAccess,4,"D:AR"
icssvc,4,"D:AR"
MSiSCSI,4,"D:AR"
PNRPsvc,4,"D:AR"
p2psvc,4,"D:AR"
p2pimsvc,4,"D:AR"
PNRPAutoReg,4,"D:AR"
wercplsupport,4,"D:AR"
RasAuto,4,"D:AR"
SessionEnv,4,"D:AR"
TermService,4,"D:AR"
UmRdpService,4,"D:AR"
RpcLocator,4,"D:AR"
RemoteRegistry,4,"D:AR"
RemoteAccess,4,"D:AR"
simptcp,4,"D:AR"
SNMPTRAP,4,"D:AR"
SSDPSRV,4,"D:AR"
upnphost,4,"D:AR"
WerSvc,4,"D:AR"
Wecsvc,4,"D:AR"
WMPNetworkSvc,4,"D:AR"
WpnService,4,"D:AR"
PushToInstall,4,"D:AR"
XboxGipSvc,4,"D:AR"
XblAuthManager,4,"D:AR"
XblGameSave,4,"D:AR"
XboxNetApiSvc,4,"D:AR"
Telnet,4,"D:AR"
FTPSVC,4,"D:AR"
IISADMIN,4,"D:AR"
W3SVC,4,"D:AR"
"@
}
